version: "3.9"

services:

  app:
    build:
      context: .
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
      - ./data/web:/vol/web
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trello
      - POSTGRES_USER=trello
      - POSTGRES_PASSWORD=123@456

  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: